name: lit_firebase_auth_platform_interface
description: A common platform interface for the lit_firebase_auth package.
homepage: https://github.com/funwithflutter/lit_firebase_auth/lit_firebase_auth_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  plugin_platform_interface: ^1.0.1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  sign_in_with_apple: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  lit_firebase_auth:
    path: ../lit_firebase_auth

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"